### ISSUE TITLE
Ripper is an UnknownParser

### ISSUE THREAD

**Issue by brandonzylstra** [pocke/rpr#29]
# How to reproduce this:

```
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin15]
$ command gem install rpr
$ echo 'puts "Hello world"' > hello.rb
$ rpr hello.rb --parser rubocop  # confirmation that it is installed and generally working
s(:send, nil, :puts,
  s(:str, "Hello world"))
rpr hello.rb --parser ripper
Traceback (most recent call last):
	5: from /Users/brandon/.rbenv/versions/2.5.0/bin/rpr:23:in `<main>'
	4: from /Users/brandon/.rbenv/versions/2.5.0/bin/rpr:23:in `load'
	3: from /Users/brandon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rpr-1.5.0/exe/rpr:7:in `<top (required)>'
	2: from /Users/brandon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rpr-1.5.0/lib/rpr.rb:23:in `run'
	1: from /Users/brandon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rpr-1.5.0/lib/rpr.rb:51:in `find_parser'
/Users/brandon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rpr-1.5.0/lib/rpr.rb:55:in `rescue in find_parser': ripper is unknown parser. (Rpr::UnknownParser)
```

**Comment by pocke** [comment]
rpr does not support `ripper` parser. You can use `sexp`, `lex` or `tokenize` for this purpose.
I released rpr version 1.6.0 to improve the error message. rpr v1.6.0 displays parser names in help and error message.

```
$ rpr --help
Usage: rpr [options]
    -f, --formatter=FORMATTER        json|pry|pp
    -o, --out=FILE
    -p, --parser=PARSER              rubyparser|sexp|tokenize|parser|lex|rubocop
    -e=CODE
    -v, --version
```
